# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 687a54dc0d16e7bd503c71b30e89bc37a5d81942b3d3431560f33d6d2b8856b9b582edc1ca5406b85c601a001d26fe3409c59d27b22e3a9873d544aa094b546a

test:
  secret_key_base: 44750d445201688242d951c9273eb13ab7b702e517853c55017e2e04d1ead17a30f5da73179fb23464f772ef084e1b4e0d9412e9d8b6fe9d09d1c491f5212a8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
